// data.js — extracted from app.js (9 declarations)

// No password fields here on purpose — see the comment on REQUIRED_USERS
// below for why shipping one in this client bundle is unsafe and was the
// actual cause of the password-wipe bug.
const INITIAL_USERS = [
  {
    name: "Kamal",
    email: "kamal@modesigns.in",
    role: "employee",
    designation: "HR/admin",
    code: "-",
    dayOff: "Sunday",
  },
  {
    name: "Dilip Gupta",
    email: "dilip.gupta@curtainsandcarpets.com",
    role: "employee",
    designation: "IT/cashier",
    code: "-",
    dayOff: "-",
  },
  { name: "Mohini", email: "mohini@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Akhilesh", email: "akhileshmofitter@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Tuesday" },
  { name: "ABHISEK SINGH", email: "modesignsabhisheksingh@gmail.com", role: "salesman", designation: "-", code: "ASB", dayOff: "-" },
  { name: "Komal", email: "komal@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Munish", email: "munish@modesigns.in", role: "Data Analytics", designation: "MIS & Data Analytics", code: "-", dayOff: "-" },
  { name: "SAROJ KUMAR DAS", email: "modesignssaroj.das@gmail.com", role: "salesman", designation: "salesmanager", code: "ASD", dayOff: "-" },
  { name: "Kajal Kumari", email: "kajal@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Umesh Partap singh", email: "modesignsumesh@gmail.com", role: "salesman", designation: "salesmanager", code: "UMDP", dayOff: "-" },
  { name: "Ruchi", email: "ruchi@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Satendar kumar", email: "satendar.mospace@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Sunday" },
  { name: "Mayuri", email: "mayuri@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Nekchand", email: "mofurnishing9971127532@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Sunday" },
  { name: "Sonika", email: "hr@modesigns.in", role: "Hr", designation: "-", code: "-", dayOff: "-" },
  { name: "ASHISH YADAV", email: "ashish.yadav@curtainsandcarpets.com", role: "salesman", designation: "HeadSalesManager", code: "-", dayOff: "-" },
  { name: "Vishal Dubey", email: "vishal.dubey@modesigns.in", role: "salesman", designation: "-", code: "VD", dayOff: "-" },
  { name: "SHIV DAYAL", email: "modesignsshivdayal.yadav@gmail.com", role: "salesman", designation: "-", code: "DS", dayOff: "-" },
  { name: "Asha", email: "asha@modesigns.in", role: "admin", designation: "EA", code: "-", dayOff: "-" },
  { name: "Ekbali", email: "modesigns.ekbali@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "Harish", email: "modesignsharish.yadav@gmail.com", role: "Accounts", designation: "-", code: "-", dayOff: "-" },
  { name: "Vikas Parjapati", email: "modesignsvikas.kumar@gmail.com", role: "Purchase", designation: "-", code: "-", dayOff: "-" },
  { name: "Nikita Kumari", email: "nikita@modesigns.in", role: "PC", designation: "-", code: "-", dayOff: "-" },
  { name: "Tafzal", email: "info@curtainsandcarpets.com", role: "Purchase", designation: "PE", code: "-", dayOff: "-" },
  { name: "MURARI SINGH", email: "modesignsmurari.singh@gmail.com", role: "salesman", designation: "Branch Manager", code: "MU", dayOff: "-" },
  { name: "Deepak Sinha", email: "modesignsdeepak.sinha@gmail.com", role: "salesman", designation: "-", code: "DK", dayOff: "-" },
  { name: "Chandan Kumar Gupta", email: "chandangupta16698@gmail.com", role: "admin", designation: "ERP Development and Sr. MIS", code: "-", dayOff: "-" },
  { name: "JeetRam", email: "modesignsjeetram@gmail.com", role: "Accounts", designation: "ASST ACCOUNT", code: "-", dayOff: "-" },
  { name: "Vinod", email: "movinody@gmail.com", role: "installer_disable", designation: "-", code: "-", dayOff: "-" },
  { name: "Pooja Kumari", email: "modesigns.pooja@gmail.com", role: "employee", designation: "PC", code: "-", dayOff: "-" },
  { name: "Nand Kishore", email: "nand@curtainsandcarpets.com", role: "salesman", designation: "-", code: "NK", dayOff: "-" },
  { name: "ANOWER ALI", email: "modesignsanower@gmail.com", role: "salesman", designation: "salesmanager", code: "ANVR", dayOff: "-" },
  { name: "Tanisha", email: "tanisha@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Vikash yadav", email: "bhadohivikasyadav@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Thursday" },
  { name: "SURESH MAURYA", email: "suresh.maurya@curtainsandcarpets.com", role: "admin", designation: "Computer", code: "-", dayOff: "-" },
  { name: "EKTA", email: "ekta@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Payal Kumari", email: "payal@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Sanjay", email: "sanjay@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Thursday" },
  { name: "PRADEEP", email: "pradeepparsipur@gmail.com", role: "salesman", designation: "salesmanager", code: "CP", dayOff: "-" },
  { name: "Sweta", email: "sweta@gmail.com", role: "salesman", designation: "-", code: "SD", dayOff: "-" },
  { name: "Omparkash", email: "op.singh@curtainsandcarpets.com", role: "installer", designation: "-", code: "-", dayOff: "Wednesday" },
  { name: "Himanshu", email: "himanshu@modesigns.in", role: "admin", designation: "-", code: "-", dayOff: "-" },
  { name: "Parmila", email: "modesigns.pramila@gmail.com", role: "Accounts", designation: "-", code: "-", dayOff: "-" },
  { name: "Rakhi", email: "rakhi@modesigns.in", role: "employee", designation: "EA", code: "-", dayOff: "-" },
  { name: "Bharti", email: "bharti.modesigns@gmail.com", role: "Accounts", designation: "-", code: "-", dayOff: "-" },
  { name: "installer1", email: "installer@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Sanjit Kumar", email: "modesigns.sanjit@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "Tanu", email: "tanu@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "RAJESH", email: "modesignsrajesh@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "Raja", email: "modesignsraja@gmail.com", role: "Accounts", designation: "-", code: "-", dayOff: "-" },
  { name: "Murari", email: "murari@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Tuesday" },
  { name: "Rajan Kumar", email: "modesignsrajan@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "DEVENDAR", email: "modesignsdevendra@gmail.com", role: "salesman", designation: "-", code: "KD", dayOff: "-" },
  { name: "Sharwan Kumar", email: "sarwankumarchorma@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Wednesday" },
  { name: "Vikas Driver", email: "vv9026561@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Hrullekha", email: "hrullekha@modesigns.in", role: "admin", designation: "MIS & Data Analytics", code: "-", dayOff: "-" },
  { name: "RAJENDRA SINGH", email: "modesignsrajendarbisht@gmail.com", role: "salesman", designation: "-", code: "RSB", dayOff: "-" },
  { name: "EKBALI", email: "modesignsekbali@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "Vinod", email: "movinody@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Tuesday" },
  { name: "Aanchal", email: "aanchal@modesigns.in", role: "PC", designation: "-", code: "-", dayOff: "-" },
  { name: "Vivek", email: "modesignsvivek@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "Deepak Soni", email: "deepak.soni@modesigns.in", role: "salesman", designation: "-", code: "DS", dayOff: "-" },
  { name: "Rahul Yadev", email: "yadevrahul731037@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Thursday" },
  { name: "Situ", email: "situ@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Vishal Ohri", email: "vishal@curtainsandcarpets.com", role: "IT", designation: "MIS & Data Analytics", code: "-", dayOff: "-" },
  { name: "Abhishek Kannojiya", email: "modesignsabhishekk@gmail.com", role: "salesman", designation: "-", code: "AK", dayOff: "-" },
  { name: "Heena", email: "heena@modesigns.in", role: "employee", designation: "PC", code: "-", dayOff: "-" },
  { name: "Brijesh", email: "brijeshshingyy@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Wednesday" },
  { name: "TAPESHWAR", email: "modesignstapeshwar.k@gmail.com", role: "salesman", designation: "-", code: "BTK", dayOff: "-" },
  { name: "RAJESH BHATIA", email: "modesignsrajesh.bhatia@gmail.com", role: "salesman", designation: "SALES MAN", code: "RB", dayOff: "-" },
  { name: "Ranjay", email: "modesigns.ranjay@gmail.com", role: "employee", designation: "Allocators", code: "-", dayOff: "-" },
  { name: "TEST GROUP", email: "chandanself1998@gmail.com", role: "Data Analytics", designation: "ERP Development & Sr. Data Analytics/MIS", code: "-", dayOff: "-" },
  { name: "Ranju", email: "modesignsranju@gmail.com", role: "Accounts", designation: "-", code: "-", dayOff: "-" },
  { name: "PAWAN SHARMA", email: "pawan.sharma@curtainsandcarpets.com", role: "salesman", designation: "HeadSalesManager", code: "BPS", dayOff: "-" },
  { name: "Komal", email: "komal@gmail.com", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Naveli Kumari", email: "naveli@modesigns.in", role: "employee", designation: "CRM", code: "-", dayOff: "-" },
  { name: "Ajit kumar", email: "pattelajitkumar@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Tuesday" },
  { name: "Pramod", email: "pramod@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Sanjay Das", email: "sanjaydas@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Bablu", email: "bablu@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Pritam Singh", email: "pritamsingh@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Sanjay Patel", email: "sanjaypatel@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Ranjan", email: "ranjan@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Shymlal", email: "shymlal@modesigns.in", role: "installer", designation: "-", code: "-", dayOff: "-" },
  { name: "Arta Chand Sahoo", email: "modesignsac.sahoo@gmail.com", role: "salesman", designation: "salesmanager", code: "AAS", dayOff: "-" },
  { name: "Neeraj Das", email: "modesignsneerajdas@gmail.com", role: "salesman", designation: "salesmanager", code: "NKD", dayOff: "-" },
  { name: "Tufani", email: "modesignsprivatelimited@gmail.com", role: "installer", designation: "-", code: "-", dayOff: "Thursday" },
];

const GENERATOR_CHECKLIST_UNITS = Object.freeze(["DG-1-MO1", "DG-2-MO1", "DG-1-MO2", "DG-2-MO2"]);
const CASH_HANDLING_SHIFTS = Object.freeze(["Morning", "Evening"]);
const CASH_DENOMINATIONS = Object.freeze([500, 200, 100, 50, 20, 10]);
const CASH_COIN_DENOMINATIONS = Object.freeze([20, 10, 5, 2, 1]);
const METER_READING_LOCATIONS = Object.freeze(["MO1", "MO2"]);
const EARTHING_CLEANING_LOCATIONS = Object.freeze(["MO1", "MO2"]);


const STORAGE_KEYS = {
  session: "motrack-session",
  authToken: "motrack-auth-token",
  rememberedEmail: "motrack-remembered-email",
  users: "motrack-users",
  tasks: "motrack-tasks",
  deletedRequiredTasks: "motrack-deleted-required-tasks",
  completions: "motrack-completions",
  absences: "motrack-absences",
  pantryAlerts: "motrack-pantry-alerts",
};


const DEFAULT_TASK_START_DATE = todayValue();


// No password field here on purpose: the client never needs one (auth is
// verified server-side via /api/login against the real stored password),
// and shipping one in this bundle would both leak a real credential in page
// source and get merged into state.users on every load — which previously
// caused ensureRequiredUsers() to inject "CHANGE_ME" back in even after a
// user set a real password, undoing it on the next save.
const REQUIRED_USERS = [
  {
    name: "Kamal",
    email: "kamal@modesigns.in",
    role: "employee",
    designation: "HR/admin",
    code: "-",
    dayOff: "Sunday",
  },
  {
    name: "Asha",
    email: "asha@modesigns.in",
    role: "admin",
    designation: "EA",
    code: "-",
    dayOff: "-",
  },
  {
    name: "Dilip Gupta",
    email: "dilip.gupta@curtainsandcarpets.com",
    role: "employee",
    designation: "IT/cashier",
    code: "-",
    dayOff: "-",
  },
];


const VEHICLE_ASSIGNMENTS = Object.freeze([
  {
    email: "sanjay@gmail.com",
    names: ["Sanjay"],
    vehicleNumber: "Eco- HR 55 AL 4922",
    vehicleType: "Four Wheeler",
  },
  {
    email: "modesigns.syadav@gmail.com",
    names: ["Sanjay Yadav"],
    vehicleNumber: "Wagon r- HR 98 J 2273",
    vehicleType: "Four Wheeler",
  },
  {
    email: "brijeshshingyy@gmail.com",
    names: ["Brijesh"],
    vehicleNumber: "Desire- HR 98 E 7168",
    vehicleType: "Four Wheeler",
  },
  {
    email: "akhileshmofitter@gmail.com",
    names: ["Akhilesh", "Akhilesh Kumar"],
    vehicleNumber: "Kia- HR 98 K 9030",
    vehicleType: "Four Wheeler",
  },
  {
    names: ["Rakesh yadav", "Rakesh Kumar Yadav"],
    vehicleNumber: "HR 98 N 8069",
    vehicleType: "Two Wheeler",
  },
  {
    email: "pattelajitkumar@gmail.com",
    names: ["Ajit Patel", "Ajit kumar", "Ajit Kumar"],
    vehicleNumber: "HR 98 N 6997",
    vehicleType: "Two Wheeler",
  },
  {
    email: "mofurnishing9971127532@gmail.com",
    names: ["Nek chand", "Nekchand", "Nek Chand"],
    vehicleNumber: "HR 98 N 8893",
    vehicleType: "Two Wheeler",
  },
  {
    email: "bhadohivikasyadav@gmail.com",
    names: ["Vikash Yadav", "Vikash yadav", "Vikash Kumar"],
    vehicleNumber: "HR 98 N 2628",
    vehicleType: "Two Wheeler",
  },
  {
    email: "op.singh@curtainsandcarpets.com",
    names: ["Omprakash", "Omparkash", "Om Prakash Singh"],
    vehicleNumber: "HR 98 V 4672",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Pramod", "Pramod Kumar"],
    vehicleNumber: "HR 98 N 9078",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Sanjay Das"],
    vehicleNumber: "HR 98 B 7814",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Bablu", "Bablu Paswan"],
    vehicleNumber: "HR 98 A 0544",
    vehicleType: "Two Wheeler",
  },
  {
    email: "modesignsharish.yadav@gmail.com",
    names: ["Harish Yadav", "Harish"],
    vehicleNumber: "HR 98 A 6467",
    vehicleType: "Two Wheeler",
  },
  {
    email: "movinody@gmail.com",
    names: ["Vinod kumar", "Vinod Kumar", "Vinod"],
    vehicleNumber: "HR 98 N 5689",
    vehicleType: "Two Wheeler",
  },
  {
    email: "modesignsprivatelimited@gmail.com",
    names: ["Tufani MO2", "Tufani"],
    vehicleNumber: "HR 98 N 5312",
    vehicleType: "Two Wheeler",
  },
  {
    email: "murari@gmail.com",
    names: ["Murari", "Murari Singh"],
    vehicleNumber: "HR 98 H 5294",
    vehicleType: "Two Wheeler",
  },
  {
    email: "satendar.mospace@gmail.com",
    names: ["Satendra kumar", "Satendar kumar", "Satendra Kumar", "Satendar Kumar"],
    vehicleNumber: "HR 98 N 1761",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Pritam Singh", "Pritam Kumar Singh"],
    vehicleNumber: "HR 98 N 9983",
    vehicleType: "Two Wheeler",
  },
  {
    email: "sanjaypatel@modesigns.in",
    names: ["Sanjay Patel"],
    vehicleNumber: "HR 98 B 5971",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Shravan", "Sharwan Kumar", "Shrawan Kumar"],
    vehicleNumber: "HR 98 N 5312",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Rajan Yadav"],
    vehicleNumber: "HR 98 B 2893",
    vehicleType: "Two Wheeler",
  },
  {
    names: ["Abhishek Shukla"],
    vehicleNumber: "HR 98 A 4094",
    vehicleType: "Two Wheeler",
  },
  {
    email: "pramod@modesigns.in",
    names: ["Pramod", "Pramod Kumar"],
    vehicleNumber: "HR 98 N 9078",
    vehicleType: "Two Wheeler",
  },
  {
    email: "sanjaydas@modesigns.in",
    names: ["Sanjay Das"],
    vehicleNumber: "HR 98 B 7814",
    vehicleType: "Two Wheeler",
  },
  {
    email: "bablu@modesigns.in",
    names: ["Bablu", "Bablu Paswan"],
    vehicleNumber: "HR 98 A 0544",
    vehicleType: "Two Wheeler",
  },
  {
    email: "pritamsingh@modesigns.in",
    names: ["Pritam Singh", "Pritam Kumar Singh"],
    vehicleNumber: "HR 98 N 9983",
    vehicleType: "Two Wheeler",
  },
  {
    email: "ranjan@modesigns.in",
    names: ["Ranjan"],
    vehicleNumber: "Desire- HR 7940",
    vehicleType: "Four Wheeler",
  },
  {
    email: "shymlal@modesigns.in",
    names: ["Shymlal", "Shyamlal", "Shyam Lal"],
    vehicleNumber: "Desire- HR 7940",
    vehicleType: "Four Wheeler",
  },
  {
    email: "installer@gmail.com",
    names: ["installer1"],
    vehicleNumber: "-",
    vehicleType: "Two Wheeler",
  },
  {
    email: "vv9026561@gmail.com",
    names: ["Vikas Driver"],
    vehicleNumber: "-",
    vehicleType: "Two Wheeler",
  },
  {
    email: "yadevrahul731037@gmail.com",
    names: ["Rahul Yadev"],
    vehicleNumber: "-",
    vehicleType: "Two Wheeler",
  },
]);


const BUDDY_ASSIGNMENTS = [
  { sheet: "MO1", employee: "ARTA CHANDRA SAHOO", department: "SALES MAN", location: "MO1", weekOff: "Tuesday", buddies: ["SAROJ KUMAR DAS"] },
  { sheet: "MO1", employee: "TAPESHWAR KAMAT", department: "SALES MAN", location: "MO1", weekOff: "Wednesday", buddies: ["Pawan Sharma"] },
  { sheet: "MO1", employee: "SAROJ KUMAR DAS", department: "SALES MAN", location: "MO1", weekOff: "Thursday", buddies: ["ARTA CHANDRA SAHOO"] },
  { sheet: "MO1", employee: "MURARI SINGH", department: "SALES MAN", location: "MO1", weekOff: "Tuesday", buddies: ["Pawan Sharma"] },
  { sheet: "MO1", employee: "CHANDRAPAL GAUTAM", department: "HELPER", location: "MO2", weekOff: "Wednesday", buddies: ["Dinesh"] },
  { sheet: "MO1", employee: "DILIP KUMAR GUPTA", department: "CASHIER", location: "MO1", weekOff: "Wednesday", buddies: ["Pawan (HR)"] },
  { sheet: "MO1", employee: "Deepa Gupta", department: "EA", location: "MO1", weekOff: "Sunday", buddies: [] },
  { sheet: "MO1", employee: "Pradeep Kumar", department: "SALES MAN", location: "MO1", weekOff: "Tuesday", buddies: ["ABHISHEK KUMAR"] },
  { sheet: "MO1", employee: "UMESH PRATAP SINGH", department: "SALES MAN", location: "MO1", weekOff: "Tuesday", buddies: ["Devendra Kumar"] },
  { sheet: "MO1", employee: "ABHISHEK KUMAR", department: "SALES MAN", location: "MO1", weekOff: "Thursday", buddies: ["Pradeep Kumar"] },
  { sheet: "MO1", employee: "Anower Ali", department: "SALES MAN", location: "MO1", weekOff: "Thursday", buddies: ["Devendra Kumar"] },
  { sheet: "MO1", employee: "Devendra Kumar", department: "SALES MAN", location: "MO1", weekOff: "Wednesday", buddies: ["UMESH PRATAP SINGH"] },
  { sheet: "MO1", employee: "Mohini", department: "CRM", location: "MO1", weekOff: "Tuesday", buddies: ["Mayuri"] },
  { sheet: "MO1", employee: "Mayuri", department: "CRM", location: "MO1", weekOff: "Thursday", buddies: ["Mohini"] },
  { sheet: "MO1", employee: "VEERENDRA", department: "ELECTRICIAN", location: "MO1", weekOff: "Tuesday", buddies: ["Abhishek (Elec.)"] },
  { sheet: "MO1", employee: "KHOKON DAS", department: "PANTRY", location: "MO1", weekOff: "Tuesday", buddies: ["Biswajit"] },
  { sheet: "MO1", employee: "BISWAJIT DAS", department: "PANTRY", location: "MO1", weekOff: "Wednesday", buddies: ["Adin"] },
  { sheet: "MO1", employee: "ADIN BISWAS", department: "PANTRY", location: "MO1", weekOff: "Thursday", buddies: ["Biswajit"] },
  { sheet: "MO2", employee: "Pawan Kumar", department: "HR & ADMIN", location: "MO2", weekOff: "Tuesday", buddies: ["Kamal"] },
  { sheet: "MO2", employee: "Sonika Dwivedi", department: "HR & ADMIN", location: "MO2", weekOff: "Sunday", buddies: ["Kamal", "Pawan", "Palak"] },
  { sheet: "MO2", employee: "Palak", department: "HR & ADMIN", location: "MO2", weekOff: "Sunday", buddies: ["Sonika"] },
  { sheet: "MO2", employee: "Kamal Singh", department: "HR & ADMIN", location: "MO2", weekOff: "Sunday", buddies: ["Pawan"] },
  { sheet: "MO2", employee: "PRITAM KUMAR SINGH", department: "ACCOUNTS", location: "MO2", weekOff: "Sunday", buddies: ["Jeet Ram", "Harish", "Pramila"] },
  { sheet: "MO2", employee: "Jeet Ram", department: "ACCOUNTS", location: "MO2", weekOff: "Wednesday", buddies: ["Pramila"] },
  { sheet: "MO2", employee: "Harish yadav", department: "ACCOUNTS", location: "MO2", weekOff: "Thursday", buddies: ["Jeetram"] },
  { sheet: "MO2", employee: "Ranju Kumari", department: "ACCOUNTS", location: "MO2", weekOff: "Thursday", buddies: ["Pramila"] },
  { sheet: "MO2", employee: "Raja Kumar", department: "ACCOUNTS", location: "MO2", weekOff: "Tuesday", buddies: ["Jeetram"] },
  { sheet: "MO2", employee: "Pramila Rawat", department: "ACCOUNTS", location: "MO2", weekOff: "Sunday", buddies: ["Raja"] },
  { sheet: "MO2", employee: "SURESH KUMAR MAURYA", department: "COMPUTER OPERATOR", location: "MO2", weekOff: "Tuesday", buddies: ["Ranjay"] },
  { sheet: "MO2", employee: "RANJAY KUMAR", department: "COMPUTER OPERATOR", location: "MO2", weekOff: "Thursday", buddies: ["Suresh Maurya"] },
  { sheet: "MO2", employee: "Ekbali Kumar", department: "COMPUTER OPERATOR", location: "MO2", weekOff: "Wednesday", buddies: ["Suresh Maurya"] },
  { sheet: "MO2", employee: "RAJESH KUMAR CHOUDHARY", department: "COMPUTER OPERATOR", location: "MO2", weekOff: "Wednesday", buddies: ["Ranjay"] },
  { sheet: "MO2", employee: "VIVEK KUMAR", department: "COMPUTER OPERATOR", location: "MO2", weekOff: "Thursday", buddies: ["Ekbali"] },
  { sheet: "MO2", employee: "Tafazal", department: "COMPUTER OPERATOR", location: "MO2", weekOff: "", buddies: ["Suresh Maurya"] },
  { sheet: "MO2", employee: "SWETA", department: "INTERIORS", location: "MO2", weekOff: "Monday", buddies: [] },
  { sheet: "MO2", employee: "Shubham Gaur", department: "MK", location: "MO2", weekOff: "Sunday", buddies: ["Ankita"] },
  { sheet: "MO2", employee: "Deepak Soni", department: "MK", location: "MO2", weekOff: "Thursday", buddies: [] },
  { sheet: "MO2", employee: "Ankita Kumari", department: "MK", location: "MO2", weekOff: "Sunday", buddies: ["Shubham"] },
  { sheet: "MO2", employee: "Abhishek Shukla", department: "MK", location: "MO2", weekOff: "Sunday", buddies: [] },
  { sheet: "MO2", employee: "PAWAN SHARMA", department: "SALES MAN", location: "MO2", weekOff: "Wednesday", buddies: ["Ashish Yadav"] },
  { sheet: "MO2", employee: "ASHISH YADAV", department: "SALES MAN", location: "MO2", weekOff: "Thursday", buddies: ["Pawan", "Pawan HR"] },
  { sheet: "MO2", employee: "Neeraj kumar Das", department: "SALES MAN", location: "MO2", weekOff: "Wednesday", buddies: ["Rajendra Singh"] },
  { sheet: "MO2", employee: "RAJENDRA SINGH", department: "SALES MAN", location: "MO2", weekOff: "Tuesday", buddies: ["Neeraj Kumar Das"] },
  { sheet: "MO2", employee: "DINESH KUMAR YADAV", department: "HELPER", location: "MO2", weekOff: "Tuesday", buddies: ["Pardeep"] },
  { sheet: "MO2", employee: "PRADEEP KUMAR", department: "HELPER", location: "MO2", weekOff: "Thursday", buddies: ["Dinesh"] },
  { sheet: "MO2", employee: "Dipti Pandey", department: "Textile Designer", location: "MO2", weekOff: "Tuesday", buddies: ["Simran"] },
  { sheet: "MO2", employee: "Simran", department: "Textile Designer", location: "MO2", weekOff: "Thursday", buddies: ["Dipti"] },
  { sheet: "MO2", employee: "Asha", department: "EA", location: "MO2", weekOff: "Sunday", buddies: [] },
  { sheet: "MO2", employee: "Munish Singh Rawat", department: "MIS", location: "MO2", weekOff: "Tuesday", buddies: ["Chandan"] },
  { sheet: "MO2", employee: "Chandan Kumar", department: "MIS", location: "MO2", weekOff: "Thursday", buddies: ["Hrullekha"] },
  { sheet: "MO2", employee: "Hrullekha", department: "MIS", location: "MO2", weekOff: "Sunday", buddies: ["Chandan"] },
  { sheet: "MO2", employee: "Nikita Parihar", department: "CRM", location: "MO2", weekOff: "Thursday", buddies: ["Aanchal"] },
  { sheet: "MO2", employee: "Aanchal", department: "PC", location: "MO2", weekOff: "Tuesday", buddies: ["Pooja"] },
  { sheet: "MO2", employee: "Ekta", department: "CRM", location: "MO2", weekOff: "Wednesday", buddies: ["Nikita"] },
  { sheet: "MO2", employee: "Tanisha", department: "CRM", location: "MO2", weekOff: "Sunday", buddies: [] },
  { sheet: "MO2", employee: "Rakesh Kumar Yadav", department: "HELPER", location: "MO2", weekOff: "Wednesday", buddies: ["Pramod"] },
  { sheet: "MO2", employee: "Pramod Kumar", department: "HELPER", location: "MO2", weekOff: "Monday", buddies: ["Rakesh"] },
  { sheet: "MO2", employee: "Pradip Kumar", department: "HELPER", location: "MO2", weekOff: "Wednesday", buddies: ["Muneesh"] },
  { sheet: "MO2", employee: "SANJAY DAS", department: "HELPER", location: "MO2", weekOff: "Wednesday", buddies: ["Pradip Kumar"] },
  { sheet: "MO2", employee: "Muneesh", department: "", location: "MO2", weekOff: "", buddies: ["Pradip Kumar"] },
  { sheet: "MO2", employee: "ARUN MISHRA", department: "ELECTRICIAN", location: "MO2", weekOff: "Wednesday", buddies: ["Abhishek"] },
  { sheet: "MO2", employee: "ABHISHEK KUMAR", department: "ELECTRICIAN", location: "MO2", weekOff: "Tuesday", buddies: ["Arun"] },
  { sheet: "MO2", employee: "OM PRAKASH SINGH", department: "FIELD WORK", location: "MO2", weekOff: "Wednesday", buddies: ["Nek Chand"] },
  { sheet: "MO2", employee: "Vinod KUMAR", department: "FITTER", location: "MO2", weekOff: "Tuesday", buddies: ["Satendra"] },
  { sheet: "MO2", employee: "AJIT KUMAR", department: "FITTER", location: "MO2", weekOff: "Tuesday", buddies: ["Vikash Kumar"] },
  { sheet: "MO2", employee: "SATENDAR KUMAR", department: "FITTER", location: "MO2", weekOff: "Sunday", buddies: ["Vinod Kumar"] },
  { sheet: "MO2", employee: "NEK CHAND", department: "FITTER", location: "MO2", weekOff: "Sunday", buddies: ["Shrawan"] },
  { sheet: "MO2", employee: "SHRAWAN KUMAR", department: "FITTER", location: "MO2", weekOff: "Wednesday", buddies: ["Satendra"] },
  { sheet: "MO2", employee: "VIKASH KUMAR", department: "FITTER", location: "MO2", weekOff: "Thursday", buddies: ["Ajit"] },
  { sheet: "MO2", employee: "SHYAM LAL PRAJAPATI", department: "DRIVER", location: "MO2", weekOff: "Monday", buddies: ["Rajan Yadav"] },
  { sheet: "MO2", employee: "Sanjay Yadav", department: "DRIVER", location: "MO2", weekOff: "Thursday", buddies: ["Akhilesh"] },
  { sheet: "MO2", employee: "Brijesh", department: "DRIVER", location: "MO2", weekOff: "Wednesday", buddies: ["Akhilesh"] },
  { sheet: "MO2", employee: "Akhilesh Kumar", department: "DRIVER", location: "MO2", weekOff: "Tuesday", buddies: ["Sanjay Yadav"] },
  { sheet: "MO2", employee: "RAMU KUMAR", department: "FITTER / HELPER", location: "MO2", weekOff: "Sunday", buddies: ["Satendra"] },
  { sheet: "MO2", employee: "BABLU PASWAN", department: "FITTER / HELPER", location: "MO2", weekOff: "Tuesday", buddies: ["Vinod"] },
  { sheet: "MO2", employee: "MANISH KUMAR", department: "FITTER / HELPER", location: "MO2", weekOff: "Wednesday", buddies: ["Shrawan"] },
  { sheet: "MO2", employee: "RAHUL YADAV", department: "FITTER / HELPER", location: "MO2", weekOff: "Thursday", buddies: ["Vikash Kumar"] },
  { sheet: "MO2", employee: "Sanjay", department: "", location: "MO2", weekOff: "", buddies: ["Ajit"] },
  { sheet: "MO2", employee: "Mahesh", department: "", location: "MO2", weekOff: "", buddies: ["Nek Chand"] },
  { sheet: "MO2", employee: "CHANDAN DAS", department: "FITTER / HELPER", location: "MO2", weekOff: "Thursday", buddies: ["Bablu Paswan"] },
  { sheet: "MO2", employee: "Upen Das", department: "Pantry", location: "MO2", weekOff: "Tuesday", buddies: [] },
];

// Transcribed from the "Aasha Ea · Contact details.pdf" staff phone directory.
const CONTACT_DIRECTORY = [
  { name: "Murari Singh", department: "Salesman", location: "MO1", phone: "9910393802", remark: "Working" },
  { name: "Abhishek Kanoujiya", department: "Salesman", location: "MO1", phone: "8130010725", remark: "Working" },
  { name: "Big Mam (Vishal sir Mother)", department: "", location: "", phone: "9811832377", remark: "Working" },
  { name: "Bavya Ohari Mam", department: "", location: "", phone: "7042101217", remark: "Working" },
  { name: "Divya Ohri Mam", department: "", location: "", phone: "9971391094", remark: "Working" },
  { name: "Pawan Sharma", department: "Salesman", location: "MO2", phone: "9971391090", remark: "Working" },
  { name: "Omprakash Singh", department: "Fitter", location: "MO2", phone: "9910393800", remark: "Working" },
  { name: "Ashish Kumar", department: "", location: "", phone: "9313532532", remark: "Not Confirm" },
  { name: "Vinod Kumar", department: "Fitter", location: "MO2", phone: "9971902532", remark: "Working" },
  { name: "Pritam Kumar Singh", department: "Accounts", location: "MO2", phone: "9971992532", remark: "Working" },
  { name: "Rakesh", department: "Helpar", location: "MO2", phone: "9958826888", remark: "Working" },
  { name: "Vishal Ohari (Sir)", department: "MD", location: "MO2", phone: "9910532532", remark: "Working" },
  { name: "Mahesh Ohari", department: "", location: "", phone: "9811995174", remark: "Working" },
  { name: "Dilip Kumar Gupta", department: "Cashier", location: "MO1", phone: "9311532532", remark: "Working" },
  { name: "Shyamlal Prajapati", department: "Draiver", location: "MO2", phone: "9910393804", remark: "Working" },
  { name: "Asha (EA)", department: "Nokia Keypad in Phone", location: "MO2", phone: "9971707171", remark: "Working" },
  { name: "Nand Kishore", department: "Marketing", location: "MO2", phone: "8130010729", remark: "Working" },
  { name: "Sonika Dwivedi", department: "HR", location: "MO2", phone: "8448595304", remark: "Working" },
  { name: "HR Custody", department: "", location: "", phone: "8448595300", remark: "Working" },
  { name: "Abhishek Singh", department: "Salesman", location: "MO2", phone: "8130010722", remark: "Working" },
  { name: "Abhishek Shukla", department: "Marketing Team Runner Boy", location: "MO2", phone: "8448595302", remark: "Working" },
  { name: "MO Account Dept.", department: "MO Account Dept.", location: "MO2", phone: "8448595297", remark: "Working" },
  { name: "HR Custody", department: "HR", location: "MO2", phone: "8130010723", remark: "Working" },
  { name: "NIKITA+EKTA+Aanchal--Multi Uses", department: "CRM (Googal; WebSite)", location: "MO2", phone: "9971129532", remark: "Working" },
  { name: "Divya", department: "", location: "", phone: "9971144532", remark: "Working" },
  { name: "Sweta Mam", department: "Tex.Dizner", location: "MO2", phone: "9971339532", remark: "Working" },
  { name: "Nek Chand", department: "Fitter", location: "MO2", phone: "9971127532", remark: "Working" },
  { name: "Heena Jaiswal", department: "CRM", location: "MO2", phone: "9971558532", remark: "Working" },
  { name: "Rajendra Singh", department: "Salesman", location: "MO2", phone: "8800053223", remark: "Working" },
  { name: "Tapeshwar Kamat", department: "Salesman", location: "MO1", phone: "8800053217", remark: "Working" },
  { name: "Satendra", department: "Fitter", location: "MO2", phone: "8800053227", remark: "Working" },
  { name: "Neeraj Kumar Das", department: "Helpar", location: "MO2", phone: "8800053229", remark: "Working" },
  { name: "Sanjay Das", department: "Helpar", location: "MO2", phone: "8800053230", remark: "Working" },
  { name: "HR Custody", department: "Nokia Keypad in Phone", location: "MO2", phone: "8800053222", remark: "Working" },
  { name: "Saroj Kumar Das", department: "sel", location: "MO1", phone: "8800053216", remark: "Working" },
  { name: "Komal Parsova", department: "EA", location: "MO2", phone: "8800053228", remark: "Working" },
  { name: "Umesh Pratap Singh", department: "Salesman", location: "MO1", phone: "8800053226", remark: "Working" },
  { name: "Ashish Yadav", department: "Salesman", location: "MO1", phone: "8800053225", remark: "Working" },
  { name: "Deepak Kumar Sinha", department: "Salesman", location: "MO2", phone: "8800053219", remark: "Working" },
  { name: "Tanu Upadhyay", department: "CRM", location: "MO2", phone: "8800053224", remark: "Working" },
  { name: "Rajesh Bhatia", department: "Salesman", location: "MO1", phone: "8800053221", remark: "Working" },
  { name: "Arta Chandra Sahoo", department: "Salesman", location: "MO1", phone: "8800053218", remark: "Working" },
  { name: "Kamal Singh", department: "HR/Admin", location: "MO2", phone: "8800053220", remark: "Working" },
  { name: "Vivek Kumar", department: "Comp. Opretor", location: "MO2", phone: "9289120955", remark: "Working" },
  { name: "Priyanka", department: "CRM", location: "MO2", phone: "9289120954", remark: "Working" },
  { name: "Suresh Kumar Mourya", department: "Comp. Opretor", location: "MO2", phone: "9289120953", remark: "Working" },
  { name: "Asha (EA)", department: "EA", location: "", phone: "9289120952", remark: "Working" },
  { name: "Akhilesh Kumar Yadav", department: "Draiver", location: "MO2", phone: "9289120951", remark: "Working" },
  { name: "Lokesh Mishra", department: "DR", location: "MO2", phone: "9289488820", remark: "Working" },
  { name: "Shiv Dayal", department: "Salesman", location: "MO1", phone: "9289488815", remark: "Working" },
  { name: "Sanjay Yadav", department: "Draiver", location: "MO2", phone: "9289488816", remark: "Working" },
  { name: "2nd Floor Comp. Opre. Use In Multipal", department: "Comp. Opretor", location: "MO2", phone: "9289488818", remark: "Working" },
  { name: "Abhishek Electricion", department: "Electricion", location: "MO2", phone: "9289488817", remark: "Working" },
  { name: "Ankita Kumari", department: "Marketing", location: "MO2", phone: "9971440385", remark: "Working" },
  { name: "Pawan Kumar", department: "HR", location: "MO2", phone: "9971440754", remark: "Working" },
  { name: "Ranju Kumari", department: "Accounts", location: "MO2", phone: "9971445146", remark: "Working" },
  { name: "HR Custody", department: "HR", location: "MO2", phone: "9971446938", remark: "Working" },
  { name: "Dilip Kumar Gupta (OTP Uses)", department: "Accounts", location: "MO1", phone: "9910906632", remark: "Working" },
  { name: "Ajit Patel", department: "Fitter", location: "MO2", phone: "9910904434", remark: "Working" },
  { name: "Deepak Soni", department: "Marketing", location: "MO2", phone: "9910907286", remark: "Working" },
  { name: "HR Custody", department: "", location: "", phone: "8448776199", remark: "Swipe" },
  { name: "Divij Sir", department: "MD", location: "MO2", phone: "9560860022", remark: "Working" },
  { name: "Purchase (Tafjal)", department: "Purchase Desk", location: "MO2", phone: "9971407171", remark: "Working" },
  { name: "Manoj Kumar", department: "Housekeepin/Sup.", location: "MO2", phone: "9667473662", remark: "Working" },
  { name: "Upen Das", department: "Pantry Use", location: "MO2", phone: "9667473062", remark: "Working" },
  { name: "Arun Mishra", department: "Electricion", location: "MO2", phone: "9667463352", remark: "Working" },
  { name: "Munish Singh Rawat", department: "MDO (MIS)", location: "MO2", phone: "9667685042", remark: "Working" },
  { name: "Nikunj Ohri", department: "", location: "", phone: "7428014564", remark: "Working" },
  { name: "Viaks Ohari (Sir)", department: "MD", location: "MO2", phone: "9999359310", remark: "Working" },
  { name: "Nancy Bhatnagar HR Custoday", department: "HR", location: "MO2", phone: "8448500851", remark: "Working" },
  { name: "Mayuri Radheylal Pal", department: "CRM", location: "MO2", phone: "9958783975", remark: "Working" },
  { name: "Divij Sir-05/05/2026", department: "Sent-Home", location: "", phone: "9958792927", remark: "Working" },
  { name: "HR Custody", department: "HR", location: "MO2", phone: "9958896518", remark: "Working" },
  { name: "Palak Jaiswal", department: "HR", location: "MO2", phone: "9958765851", remark: "Working" },
  { name: "Vishal Dubey", department: "Salesman", location: "MO2", phone: "9810983791", remark: "Working" },
  { name: "HR Custody", department: "", location: "", phone: "9599095062", remark: "Swipe" },
  { name: "Kumari Pooja", department: "CRM ( PC Uses )", location: "MO2", phone: "9667830864", remark: "Working" },
  { name: "Priti saini", department: "HR", location: "MO2", phone: "9667969724", remark: "Working" },
  { name: "Sakasham", department: "HR", location: "MO2", phone: "9667208410", remark: "Working" },
  { name: "Nikita", department: "CRM", location: "MO2", phone: "9667208497", remark: "Working" },
  { name: "Ekta", department: "CRM", location: "MO2", phone: "9667208473", remark: "Working" },
  { name: "Deepa Gopta", department: "EA", location: "MO1", phone: "9667207812", remark: "Working" },
  { name: "HR Custody", department: "EA", location: "MO2", phone: "9910441791", remark: "Working" },
  { name: "Aanchal", department: "CRM", location: "MO2", phone: "9971888739", remark: "Working" },
  { name: "Anwar Ali", department: "Salesman", location: "MO1", phone: "9971188946", remark: "Working" },
  { name: "HR Custody", department: "", location: "", phone: "9958748383", remark: "Working" },
  { name: "Devendra Kumar", department: "Salesman", location: "MO1", phone: "9958913602", remark: "Working" },
  { name: "Pradeep Kumar", department: "Salesman", location: "MO1", phone: "9773709289", remark: "Working" },
  { name: "MO Account Dept.", department: "MO Account Dept.", location: "MO2", phone: "9773967444", remark: "Working" },
  { name: "Anjali", department: "Tex.Dizner", location: "MO2", phone: "9773678733", remark: "Working" },
  { name: "Simran Pahwa", department: "Designer", location: "MO2", phone: "9773750078", remark: "Working" },
  { name: "Tanisha aggarwal", department: "CRM", location: "MO2", phone: "9773726676", remark: "Working" },
  { name: "Divij Sir-02/07/2026", department: "MDO", location: "MO2", phone: "8448333441", remark: "Working" },
  { name: "Mohini", department: "CRM", location: "MO2", phone: "8448333298", remark: "Working" },
  { name: "Situ Kumari", department: "CRM", location: "MO2", phone: "8448301029", remark: "Working" },
  { name: "Prince Yadav", department: "Furniture", location: "MO2", phone: "8448627755", remark: "Working" },
  { name: "Shrawan Kumar", department: "Fitter", location: "MO2", phone: "8448618811", remark: "Working" },
  { name: "Chandan Kumar", department: "MDO (MIS)", location: "MO2", phone: "9217040761", remark: "Working" },
  { name: "MDO Multipul Uses", department: "MDO (MIS)", location: "MO2", phone: "9217060247", remark: "Working" },
];


const CHECKLIST_TEMPLATES = {
  "ac checklist": {
    title: "AC CHECKLIST",
    questions: [
      {
        id: "basement_carpet_a_off_time",
        label: "What is the Basement Carpet A Off Time?",
        type: "time",
      },
      {
        id: "basement_carpet_b_off_time",
        label: "What is the Basement Carpet B Off Time?",
        type: "time",
      },
      {
        id: "basement_flooring_off_time",
        label: "What is the Basement Flooring Off Time?",
        type: "time",
      },
      {
        id: "basement_marketing_off_time",
        label: "What is the Basement Marketing Off Time?",
        type: "time",
      },
      {
        id: "basement_backside_a_off_time",
        label: "What is the Basement Backside A Off Time?",
        type: "time",
      },
      {
        id: "basement_backside_b_off_time",
        label: "What is the Basement Backside B Off Time?",
        type: "time",
      },
      {
        id: "vishal_sir_cabin_off_time",
        label: "What is the Vishal Sir Cabin Off Time?",
        type: "time",
      },
      {
        id: "mdo_cabin",
        label: "What is the MDO Cabin Off Time?",
        type: "time",
      },
      {
        id: "sweta_maam_cabin_new",
        label: "What is the Sweta Ma'am Cabin (NEW) Off Time?",
        type: "time",
      },
      {
        id: "crm_cabin",
        label: "What is the CRM Cabin Off Time?",
        type: "time",
      },
      {
        id: "divij_sir_cabin",
        label: "What is the Divij Sir Cabin Off Time?",
        type: "time",
      },
      {
        id: "ground_bar_area_off_time",
        label: "What is the Ground Bar Area Off Time?",
        type: "time",
      },
      {
        id: "conference_room_sweta_maam",
        label: "What is the Conference Room / Sweta Ma'am Off Time?",
        type: "time",
      },
      {
        id: "first_floor_hr_room_off_time",
        label: "What is the 1st Floor HR Room Off Time?",
        type: "time",
      },
      {
        id: "second_floor_accounts_room_off_time",
        label: "What is the 2nd Floor Accounts Room Off Time?",
        type: "time",
      },
      {
        id: "first_floor_pantry_a_off_time",
        label: "What is the 1st Floor Pantry A Off Time?",
        type: "time",
      },
      {
        id: "first_floor_pantry_b_off_time",
        label: "What is the 1st Floor Pantry B Off Time?",
        type: "time",
      },
      {
        id: "first_floor_marketing_a_off_time",
        label: "What is the 1st Floor Marketing A Off Time?",
        type: "time",
      },
      {
        id: "first_floor_marketing_b_off_time",
        label: "What is the 1st Floor Marketing B Off Time?",
        type: "time",
      },
      {
        id: "second_floor_server_room_off_time",
        label: "What is the 2nd Floor Server Room Off Time?",
        type: "time",
      },
      {
        id: "ground_reception_area_off_time",
        label: "What is the Ground Reception Area Off Time?",
        type: "time",
      },
    ],
  },
  "ac filter cleaning for every 15 days to be verified by kamla by cctv": {
    title: "AC FILTER CLEANING CHECKLIST",
    questions: [
      {
        id: "basement_carpet_a_off_time",
        label: "Is the Basement Carpet A AC off?",
        type: "checkbox",
      },
      {
        id: "basement_carpet_b_off_time",
        label: "Is the Basement Carpet B AC off?",
        type: "checkbox",
      },
      {
        id: "basement_flooring_off_time",
        label: "Is the Basement Flooring AC off?",
        type: "checkbox",
      },
      {
        id: "basement_marketing_off_time",
        label: "Is the Basement Marketing AC off?",
        type: "checkbox",
      },
      {
        id: "basement_backside_a_off_time",
        label: "Is the Basement Backside A AC off?",
        type: "checkbox",
      },
      {
        id: "basement_backside_b_off_time",
        label: "Is the Basement Backside B AC off?",
        type: "checkbox",
      },
      {
        id: "vishal_sir_cabin_off_time",
        label: "Is the Vishal Sir Cabin AC off?",
        type: "checkbox",
      },
      {
        id: "mdo_cabin",
        label: "Is the MDO Cabin AC off?",
        type: "checkbox",
      },
      {
        id: "sweta_maam_cabin_new",
        label: "Is the Sweta Ma'am Cabin (NEW) AC off?",
        type: "checkbox",
      },
      {
        id: "crm_cabin",
        label: "Is the CRM Cabin AC off?",
        type: "checkbox",
      },
      {
        id: "divij_sir_cabin",
        label: "Is the Divij Sir Cabin AC off?",
        type: "checkbox",
      },
      {
        id: "ground_bar_area_off_time",
        label: "Is the Ground Bar Area AC off?",
        type: "checkbox",
      },
      {
        id: "conference_room_sweta_maam",
        label: "Is the Conference Room / Sweta Ma'am AC off?",
        type: "checkbox",
      },
      {
        id: "first_floor_hr_room_off_time",
        label: "Is the 1st Floor HR Room AC off?",
        type: "checkbox",
      },
      {
        id: "second_floor_accounts_room_off_time",
        label: "Is the 2nd Floor Accounts Room AC off?",
        type: "checkbox",
      },
      {
        id: "first_floor_pantry_a_off_time",
        label: "Is the 1st Floor Pantry A AC off?",
        type: "checkbox",
      },
      {
        id: "first_floor_pantry_b_off_time",
        label: "Is the 1st Floor Pantry B AC off?",
        type: "checkbox",
      },
      {
        id: "first_floor_marketing_a_off_time",
        label: "Is the 1st Floor Marketing A AC off?",
        type: "checkbox",
      },
      {
        id: "first_floor_marketing_b_off_time",
        label: "Is the 1st Floor Marketing B AC off?",
        type: "checkbox",
      },
      {
        id: "second_floor_server_room_off_time",
        label: "Is the 2nd Floor Server Room AC off?",
        type: "checkbox",
      },
      {
        id: "ground_reception_area_off_time",
        label: "Is the Ground Reception Area AC off?",
        type: "checkbox",
      },
      {
        id: "supporting_files",
        label: "Upload supporting files if needed.",
        labelHindi: "यदि आवश्यक हो तो सहायक फ़ाइलें अपलोड करें।",
        type: "file",
        hint: "Upload up to 10 supported files. Max 3 MB per file — photos are compressed automatically.",
      },
    ],
  },
  "ro checklist": {
    title: "RO CHECKLIST",
    questions: [
      {
        id: "back_wash",
        label: "What is the BACK WASH status?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "back_wash_photo",
        label: "Upload image for BACK WASH.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "chemical_dose",
        label: "What is the CHEMICAL DOSE status?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "chemical_dose_photo",
        label: "Upload image for CHEMICAL DOSE.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "water_flow",
        label: "What is the WATER FLOW reading?",
        type: "number",
      },
      {
        id: "water_flow_photo",
        label: "Upload image for WATER FLOW.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "wastage_flow",
        label: "What is the WASTAGE FLOW reading?",
        type: "number",
      },
      {
        id: "wastage_flow_photo",
        label: "Upload image for WASTAGE FLOW.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "filter_change",
        label: "What is the FILTER CHANGE status?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "filter_change_photo",
        label: "Upload image for FILTER CHANGE.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "service_required",
        label: "What is the SERVICE status?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "service_required_photo",
        label: "Upload image for SERVICE.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "generator checklist": {
    title: "GENERATOR CHECKLIST",
    questions: [
      {
        id: "generator_no",
        label: "What is the Generator No?",
        type: "select",
        options: ["", "DG-1", "DG-2"],
      },
      {
        id: "generator_no_photo",
        label: "Upload image for Generator No.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "reading_hours",
        label: "What is the READING HRS value?",
        type: "number",
        placeholder: "Enter reading hours",
        ocrUnitHint: "hrs",
      },
      {
        id: "reading_hours_photo",
        label: "Upload image for READING HRS.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "coolant_check",
        label: "What is the COLLENT CHECK status?",
        type: "select",
        options: ["", "OK", "Not Ok"],
      },
      {
        id: "coolant_check_photo",
        label: "Upload image for COLLENT CHECK.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "oil_check",
        label: "What is the OIL CHECK status?",
        type: "select",
        options: ["", "OK", "Not Ok"],
      },
      {
        id: "oil_check_photo",
        label: "Upload image for OIL CHECK.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "mobil_oil_check",
        label: "What is the MOBEL OIL CHECK status?",
        type: "select",
        options: ["", "OK", "Not Ok"],
      },
      {
        id: "mobil_oil_check_photo",
        label: "Upload image for MOBEL OIL CHECK.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "temperature",
        label: "What is the TEMPERATURE reading?",
        type: "number",
        placeholder: "Enter temperature",
      },
      {
        id: "temperature_photo",
        label: "Upload image for TEMPERATURE.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "battery_voltage",
        label: "What is the BATTERY VOLTAGE reading?",
        type: "number",
        placeholder: "Enter battery voltage",
      },
      {
        id: "battery_voltage_photo",
        label: "Upload image for BATTERY VOLTAGE.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "service_required",
        label: "What is the SERVICE status?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "service_required_photo",
        label: "Upload image for SERVICE.",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "servo checklist": {
    title: "SERVO CHECKLIST",
    questions: [
      {
        id: "temperature_red_l1",
        label: "What is the TEMPERATURE Red-L1 reading?",
        type: "number",
        placeholder: "Enter Red-L1 temperature",
      },
      {
        id: "temperature_red_l1_file",
        label: "Upload file for TEMPERATURE Red-L1.",
        type: "file",
        hint: "Upload supporting files for this reading.",
      },
      {
        id: "temperature_yellow_l2",
        label: "What is the TEMPERATURE Yellow-L2 reading?",
        type: "number",
        placeholder: "Enter Yellow-L2 temperature",
      },
      {
        id: "temperature_yellow_l2_file",
        label: "Upload file for TEMPERATURE Yellow-L2.",
        type: "file",
        hint: "Upload supporting files for this reading.",
      },
      {
        id: "temperature_blue_l3",
        label: "What is the TEMPERATURE Blue-L3 reading?",
        type: "number",
        placeholder: "Enter Blue-L3 temperature",
      },
      {
        id: "temperature_blue_l3_file",
        label: "Upload file for TEMPERATURE Blue-L3.",
        type: "file",
        hint: "Upload supporting files for this reading.",
      },
      {
        id: "voltage",
        label: "What is the VOLTAGE reading?",
        type: "number",
        placeholder: "Enter voltage",
      },
      {
        id: "voltage_file",
        label: "Upload file for VOLTAGE.",
        type: "file",
        hint: "Upload supporting files for this reading.",
      },
      {
        id: "control",
        label: "What is the CONTROL status?",
        type: "select",
        options: ["", "OK", "Not Ok"],
      },
      {
        id: "service_done",
        label: "Is the service done?",
        type: "select",
        options: ["", "Yes", "No"],
      },
    ],
  },
  "it works - computers - telephone - camera": {
    title: "IT WORKS - COMPUTERS - TELEPHONE - CAMERA",
    questions: [
      {
        id: "check_network_speed_wifi",
        label: "Check network speed of all WiFi",
        labelHindi: "क्या सभी वाईफाई की नेटवर्क स्पीड चेक की गई?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "check_lease_line_working",
        label: "Check Lease line is working",
        labelHindi: "क्या लीज लाइन सही तरह से काम कर रही है?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "check_telephone_line_working",
        label: "Check Telephone line is working",
        labelHindi: "क्या टेलीफोन लाइन सही तरह से काम कर रही है?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "send_calls_missed_list",
        label: "Send list of calls missed at 5:00PM",
        labelHindi: "क्या शाम 5:00 बजे मिस्ड कॉल्स की सूची भेज दी गई?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "check_showroom_location_google_map",
        label: "Check location of both showrooms on Google Map (MIS)",
        labelHindi: "क्या दोनों शोरूम की लोकेशन गूगल मैप पर चेक की गई? (MIS)",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "check_website_working",
        label: "Check website is working (MIS)",
        labelHindi: "क्या वेबसाइट सही तरह से काम कर रही है? (MIS)",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "check_camera_direction_workability",
        label: "Check direction and workability of all camera",
        labelHindi: "क्या सभी कैमरों की दिशा और कार्यक्षमता चेक की गई?",
        type: "select",
        options: ["", "Yes", "No"],
      },
    ],
  },
  "inventory management - by entry & with guidance": {
    title: "INVENTORY MANAGEMENT",
    questions: [
      {
        id: "inventory_what_done",
        label: "What inventory work was done today?",
        labelHindi: "आज इन्वेंट्री में कौन-कौन सा काम किया गया?",
        type: "textarea",
      },
      {
        id: "inventory_how_done",
        label: "How was the inventory work done?",
        labelHindi: "इन्वेंट्री का काम कैसे किया गया?",
        type: "textarea",
      },
      {
        id: "inventory_frequency_followed",
        label: "How frequently was it checked or updated?",
        labelHindi: "इसे कितनी बार चेक या अपडेट किया गया?",
        type: "textarea",
      },
    ],
  },
  "company major password keeper": {
    title: "COMPANY MAJOR PASSWORD KEEPER",
    questions: [
      {
        id: "password_keeper_google_form",
        label: "Was the company major password record checked in Google Form?",
        labelHindi: "क्या कंपनी के मुख्य पासवर्ड रिकॉर्ड को गूगल फॉर्म में चेक किया गया?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "password_keeper_notes",
        label: "Share the update or note.",
        labelHindi: "अपडेट या टिप्पणी साझा करें।",
        type: "textarea",
      },
    ],
  },
  "data backup - tally software only": {
    title: "DATA BACKUP - TALLY SOFTWARE ONLY",
    questions: [
      {
        id: "tally_backup_done",
        label: "Was the Tally software backup completed?",
        labelHindi: "क्या टैली सॉफ्टवेयर का बैकअप पूरा किया गया?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "tally_backup_notes",
        label: "Share backup details or note.",
        labelHindi: "बैकअप का विवरण या टिप्पणी साझा करें।",
        type: "textarea",
      },
    ],
  },
  "cash handling checklist": {
    title: "CASH HANDLING CHECKLIST",
    questions: [
      {
        id: "cash_locker_safety",
        label: "Is the cash locker locked safely?",
        labelHindi: "क्या कैश लॉकर सुरक्षित रूप से बंद है?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "cash_handling_notes",
        label: "Share the cash handling note.",
        labelHindi: "कैश हैंडलिंग से जुड़ी टिप्पणी साझा करें।",
        type: "textarea",
      },
    ],
  },
  "meter reading in both mo1 and mo2": {
    title: "METER READING CHECKLIST",
    questions: [
      {
        id: "kvah_meter_reading",
        label: "What is the KVAH meter reading?",
        labelHindi: "KVAH मीटर रीडिंग क्या है?",
        type: "number",
        placeholder: "Enter KVAH reading",
      },
      {
        id: "kvah_meter_photo",
        label: "Upload image of the KVAH meter reading.",
        labelHindi: "KVAH मीटर रीडिंग की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "kwah_meter_reading",
        label: "What is the KWAH meter reading?",
        labelHindi: "KWAH मीटर रीडिंग क्या है?",
        type: "number",
        placeholder: "Enter KWAH reading",
      },
      {
        id: "kwah_meter_photo",
        label: "Upload image of the KWAH meter reading.",
        labelHindi: "KWAH मीटर रीडिंग की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "earthing and cleaning once in a month": {
    title: "EARTHING AND CLEANING CHECKLIST",
    questions: [
      {
        id: "earth_recharge_done",
        label: "Is the earth recharge done?",
        labelHindi: "क्या अर्थ रिचार्ज किया गया है?",
        type: "checkbox",
      },
      {
        id: "earth_recharge_photo",
        label: "Upload image of the earth recharge.",
        labelHindi: "अर्थ रिचार्ज की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "all camera functioning weekly by kamal": {
    title: "CAMERA FUNCTIONING CHECKLIST",
    questions: [
      {
        id: "camera_functioning_done",
        label: "Is all camera functioning?",
        labelHindi: "क्या सभी कैमरे काम कर रहे हैं?",
        type: "checkbox",
        followUpOnNo: {
          id: "camera_not_working_floor",
          label: "Which floor's camera is not working?",
          labelHindi: "किस फ्लोर का कैमरा काम नहीं कर रहा है?",
          type: "repeatable",
          placeholder: "Enter floor / camera detail",
        },
      },
    ],
  },
  "morning reading": {
    title: "MORNING READING CHECKLIST",
    questions: [
      {
        id: "vehicle_number",
        label: "What is the vehicle number?",
        labelHindi: "वाहन नंबर क्या है?",
        type: "text",
        placeholder: "Enter vehicle number",
      },
      {
        id: "vehicle_type",
        label: "What type of vehicle?",
        labelHindi: "वाहन का प्रकार क्या है?",
        type: "select",
        options: ["", "Two Wheeler", "Four Wheeler"],
      },
      {
        id: "meter_reading",
        label: "Enter the meter reading.",
        labelHindi: "मीटर रीडिंग दर्ज करें।",
        type: "number",
        placeholder: "Enter meter reading",
        ocrUnitHint: "km",
      },
      {
        id: "meter_reading_photo",
        label: "Upload image of the meter reading.",
        labelHindi: "मीटर रीडिंग की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "evening reading": {
    title: "EVENING READING CHECKLIST",
    questions: [
      {
        id: "vehicle_number",
        label: "What is the vehicle number?",
        labelHindi: "वाहन नंबर क्या है?",
        type: "text",
        placeholder: "Enter vehicle number",
      },
      {
        id: "vehicle_type",
        label: "What type of vehicle?",
        labelHindi: "वाहन का प्रकार क्या है?",
        type: "select",
        options: ["", "Two Wheeler", "Four Wheeler"],
      },
      {
        id: "meter_reading",
        label: "Enter the meter reading.",
        labelHindi: "मीटर रीडिंग दर्ज करें।",
        type: "number",
        placeholder: "Enter meter reading",
        ocrUnitHint: "km",
      },
      {
        id: "meter_reading_photo",
        label: "Upload image of the meter reading.",
        labelHindi: "मीटर रीडिंग की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "vehicle cleaning": {
    title: "VEHICLE CLEANING",
    questions: [
      {
        id: "outside_cleaning_done",
        label: "Is cleaning done on the outside?",
        labelHindi: "क्या बाहर की सफाई की गई है?",
        type: "checkbox",
      },
      {
        id: "outside_cleaning_photo",
        label: "Upload image of the outside cleaning.",
        labelHindi: "बाहर की सफाई की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "inside_cleaning_done",
        label: "Is cleaning done on the inside?",
        labelHindi: "क्या अंदर की सफाई की गई है?",
        type: "checkbox",
      },
      {
        id: "inside_cleaning_photo",
        label: "Upload image of the inside cleaning.",
        labelHindi: "अंदर की सफाई की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
    ],
  },
  "fuel checklist": {
    title: "FUEL CHECKLIST",
    questions: [
      {
        id: "vehicle_number",
        label: "What is the vehicle number?",
        labelHindi: "वाहन नंबर क्या है?",
        type: "text",
        placeholder: "Enter vehicle number",
      },
      {
        id: "vehicle_type",
        label: "What type of vehicle?",
        labelHindi: "वाहन का प्रकार क्या है?",
        type: "select",
        options: ["", "Two Wheeler", "Four Wheeler"],
      },
      {
        id: "odometer_reading",
        label: "What is the current odometer reading (km)?",
        labelHindi: "वर्तमान ओडोमीटर रीडिंग (किमी) क्या है?",
        type: "number",
        placeholder: "Enter current km reading",
      },
      {
        id: "odometer_photo",
        label: "Upload image of the meter reading.",
        labelHindi: "मीटर रीडिंग की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "fuel_amount",
        label: "Enter quantity of fuel (in liters).",
        labelHindi: "ईंधन की मात्रा दर्ज करें (लीटर में)।",
        type: "number",
        placeholder: "Enter fuel quantity",
        ocrUnitHint: "amount",
      },
      {
        id: "fuel_amount_photo",
        label: "Upload image of the petrol slip.",
        labelHindi: "पेट्रोल पर्ची की फोटो अपलोड करें।",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery.",
      },
      {
        id: "fuel_cost_amount",
        label: "Enter the amount (₹).",
        labelHindi: "राशि दर्ज करें (₹)।",
        type: "number",
        placeholder: "Enter amount paid",
      },
    ],
  },
  "counter billing": {
    title: "COUNTER BILLING",
    questions: [
      {
        id: "counter_billing_done",
        label: "Was counter billing handled properly?",
        labelHindi: "क्या काउंटर बिलिंग सही तरीके से की गई?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "counter_billing_notes",
        label: "Share billing notes if any.",
        labelHindi: "यदि कोई बिलिंग टिप्पणी हो तो साझा करें।",
        type: "textarea",
      },
    ],
  },
  "assist - when needed to v1/v2 work": {
    title: "ASSIST - WHEN NEEDED TO V1/V2 WORK",
    questions: [
      {
        id: "assist_work_done",
        label: "Was assistance provided where needed?",
        labelHindi: "जहाँ आवश्यकता थी, क्या वहाँ सहायता प्रदान की गई?",
        type: "select",
        options: ["", "Yes", "No"],
      },
      {
        id: "assist_team_notes",
        label: "Which team or work was assisted?",
        labelHindi: "किस टीम या किस काम में सहायता दी गई?",
        type: "textarea",
      },
    ],
  },
  "allrounder multi tasking works": {
    title: "ALLROUNDER (MULTI TASKING WORKS)",
    questions: [
      {
        id: "allrounder_work_summary",
        label: "Share the multi-tasking work summary.",
        labelHindi: "आज किए गए मल्टी-टास्किंग कार्यों का सारांश साझा करें।",
        type: "textarea",
      },
    ],
  },
  "compare walkins": {
    title: "COMPARE WALKINS",
    questions: [
      {
        id: "mo1_crm_walkins",
        label: "How many walk-ins in MO1 yesterday? According to CRM?",
        type: "number",
      },
      {
        id: "mo1_screenshot",
        label: "Screenshot of customer of MO1?",
        type: "file",
        hint: "Upload up to 10 supported files. Max 3 MB per file — photos are compressed automatically.",
      },
      {
        id: "mo1_cctv_walkins",
        label: "How many customer do you find according to CCTV in MO1?",
        type: "number",
      },
      {
        id: "mo2_crm_walkins",
        label: "How many walk-ins in MO2 yesterday? According to CRM?",
        type: "number",
      },
      {
        id: "mo2_screenshot",
        label: "Screenshot of customer of MO2?",
        type: "file",
        hint: "Upload up to 10 supported files. Max 3 MB per file — photos are compressed automatically.",
      },
      {
        id: "mo2_cctv_walkins",
        label: "How many customer do you find according to CCTV in MO2?",
        type: "number",
      },
    ],
  },
  "good setting": {
    title: "GOOD SETTING",
    questions: [
      {
        id: "good_setting_photo",
        label: "Can you upload the image/photo?",
        labelHindi: "क्या आप फोटो/इमेज अपलोड कर सकते हैं?",
        type: "photo",
        hint: "Take a photo with your phone camera, or upload one from your gallery/desktop.",
      },
    ],
  },
};


const SITE_VISIT_COUNT = 10;
const SITE_VISIT_TITLE = "SITE VISIT CHECKLIST";

// The real "Construction Site Visit" intake form (Google Apps Script).
// Each link includes a signed motrackContext so its completed visit can be
// recorded automatically when the form calls back to MoTrack after saving.
// no per-record editing), so every visit link opens the same URL — MoTrack
// just marks that visit done locally since it can't see the form's own
// submissions.
// The signed callback above is the source of truth for completion status.
const CONSTRUCTION_SITE_FORM_URL =
  "https://script.google.com/a/macros/modesigns.in/s/AKfycbyVVDKB2D89vv5xXXWGcBfFThyyzbpi03kLqaZkX9CKjunxsdyU1aaYQSRkyt8G5l6x/exec";


const PANTRY_CHECKLISTS = {
  MO1: [
    { item: "Small Bowl", quantity: 4 },
    { item: "Large Bowl", quantity: 8 },
    { item: "Lunch Plate (glass)", quantity: 5 },
    { item: "Soupe Spoon", quantity: 2 },
    { item: "Lunch Spoon big size", quantity: 5 },
    { item: "Vegetable Peeler", quantity: 1 },
    { item: "Knife", quantity: 1 },
    { item: "Small Lunch Spoon", quantity: 5 },
    { item: "Tea Strainer", quantity: 1 },
    { item: "Borosil Small Glass", quantity: 6 },
    { item: "Borosil Large Glass", quantity: 4 },
    { item: "Long Type Saucer Tea Cup Plate", quantity: 19 },
    { item: "Water Bottle Glass (Sir Use)", quantity: 1 },
    { item: "Tea Cup White with Plate (Sir n Guest Use)", quantity: 6 },
    { item: "Tea Cup Transparent", quantity: 3 },
    { item: "Plastic Small Tray", quantity: 1 },
    { item: "Mini Plastic Tray", quantity: 1 },
    { item: "Electric Kettle", quantity: 1 },
    { item: "Microwave Oven", quantity: 1 },
    { item: "Deep Freezer", quantity: 1 },
    { item: "Nescafe Coffee Machine", quantity: 1 },
    { item: "Lunch Dining Table Wooden Stone", quantity: 1 },
    { item: "Wooden Dining Bench", quantity: 6 },
    { item: "Wooden Covered Almeera", quantity: 2 },
    { item: "Plastic Lunch Plate", quantity: 6 },
    { item: "Plastic Lunch Bowl", quantity: 2 },
    { item: "Fork", quantity: 6 },
    { item: "Landline Phone", quantity: 1 },
  ],
  MO2: [
    { item: "Small Bowl", quantity: 9 },
    { item: "Large Bowl", quantity: 4 },
    { item: "Lunch Plate", quantity: 8 },
    { item: "Medium Plate", quantity: 9 },
    { item: "Soupe Spoon", quantity: 3 },
    { item: "Foge Spoon", quantity: 7 },
    { item: "Lunch Spoon big size", quantity: 9 },
    { item: "Mortar Pestle", quantity: 1 },
    { item: "Vegetable Peeler", quantity: 1 },
    { item: "Lemon Squeezer", quantity: 1 },
    { item: "Knife", quantity: 1 },
    { item: "Tong", quantity: 2 },
    { item: "Coconut Hole Cutter", quantity: 1 },
    { item: "Small Lunch Spoon", quantity: 14 },
    { item: "Scissors", quantity: 1 },
    { item: "Tea Strainer", quantity: 1 },
    { item: "Wooden Coaster Round", quantity: 13 },
    { item: "Wooden Coaster Square", quantity: 12 },
    { item: "Masala Strainer", quantity: 1 },
    { item: "Golden Plated Tea Cup", quantity: 18 },
    { item: "Golden Plated Saucer Plate", quantity: 18 },
    { item: "Borosil Small Glass", quantity: 7 },
    { item: "Borosil Large Glass", quantity: 14 },
    { item: "Long Type Saucer Tea Cup Plate", quantity: 52 },
    { item: "Transparent Tea Cup Saucer Plate", quantity: 22 },
    { item: "Water Bottle Glass", quantity: 7 },
    { item: "Tea Cup White", quantity: 38 },
    { item: "Tea Cup White And Blue", quantity: 12 },
    { item: "Tea Cup Transparent", quantity: 7 },
    { item: "Mini Tea Kettle Stone", quantity: 2 },
    { item: "Small Metal Container", quantity: 6 },
    { item: "Small Metal Bowl", quantity: 4 },
    { item: "Small Metal Tray", quantity: 1 },
    { item: "Plastic Small Tray", quantity: 2 },
    { item: "Wooden Tray", quantity: 3 },
    { item: "Plastic Mug", quantity: 1 },
    { item: "Mini Plastic Tray", quantity: 1 },
    { item: "Tea Saucepan Steel", quantity: 1 },
    { item: "Electric Kettle", quantity: 2 },
    { item: "Tea Thermos In 5 Leetor", quantity: 2 },
    { item: "Mini Coffee Maker", quantity: 1 },
    { item: "Induction (Chuhla)", quantity: 1 },
    { item: "Microwave Oven", quantity: 1 },
    { item: "Deep Freezer", quantity: 1 },
    { item: "Nescafe Coffee Machine", quantity: 1 },
    { item: "Lunch Dining Table Wooden Stone", quantity: 3 },
    { item: "Wooden Dining Bench", quantity: 5 },
    { item: "Wooden Covered Almeera", quantity: 3 },
    { item: "Wooden Metal Table", quantity: 1 },
    { item: "Electric Wall Fan", quantity: 1 },
    { item: "Wall Painting", quantity: 1 },
    { item: "Wall Mirror", quantity: 1 },
    { item: "Water Bottle 20 (Leetor)", quantity: 1 },
    { item: "Big Lunch Mate", quantity: 1 },
    { item: "Small Lunch Mate", quantity: 2 },
    { item: "Plastic Lunch Plate", quantity: 3 },
    { item: "Plastic Lunch Bowl", quantity: 2 },
    { item: "Steel Dustbin", quantity: 1 },
    { item: "Landline Phone", quantity: 1 },
  ],
};


const state = {
  users: [],
  tasks: [],
  deletedRequiredTaskIds: [],
  completions: {},
  absences: {},
  pantryAlerts: [],
  pantryAlertsExpanded: false,
  passwordResetRequests: [],
  query: "",
  role: "all",
  dayOff: "all",
  currentView: getInitialView(),
  activeUser: null,
  isSidebarCollapsed: false,
  homeSearch: "",
  adminDate: todayValue(),
  pcMonitorDate: todayValue(),
  adminBoardPage: 1,
  pcSubmittedPage: 1,
  userTablePage: 1,
  contactsQuery: "",
  contactsPage: 1,
  complianceStartDate: "",
  complianceEndDate: "",
  employeeTaskPage: 1,
  approvalsPendingPage: 1,
  approvalsCompletedPage: 1,
  approvalsNotCompletedPage: 1,
  approvalsApprovedPage: 1,
  approvalsTab: "pending",
  liveLocations: {},
  myLocationWatchId: null,
  myLocationExpiryTimer: null,
  myLocationExpiresAt: null,
  myLocationLastPushAt: 0,
  liveMapInstance: null,
  checklistMapInstance: null,
  checklistMapMarker: null,
  liveMapMarkers: {},
  liveMapRefreshTimer: null,
  visibleEmployeeTasks: [],
  visibleWalkinTasks: [],
  todayWalkinCustomers: [],
  activeChecklistTask: null,
  activeNotCompletedTask: null,
  activeSubmissionDetailsKey: null,
  activeGeneratorUnit: null,
  activeCashHandlingShift: null,
  activeMeterReadingLocation: null,
  activeEarthingCleaningLocation: null,
  pantryFormLocation: null,
  editingTaskId: null,
  vehicleAssignments: {},
  vehicleAssignmentRequests: {},
  vehicleChangeRequests: [],
  vehicleAllocations: {},
  checklistFollowUps: {},
  pcMonitorTab: "pending",
  pcPendingPage: 1,
  pcNotCompletedPage: 1,
  pcCompletedPage: 1,
  vehicleRequestFormOpen: false,
  vehicleRequestDraft: "",
  companyVehicles: [],
  companyVehicleWarnings: [],
  sheetLeaves: [],
  sheetLeaveError: null,
};


const elements = {
  authView: document.querySelector("#authView"),
  dashboardView: document.querySelector("#dashboardView"),
  loginForm: document.querySelector("#loginForm"),
  emailInput: document.querySelector("#emailInput"),
  passwordInput: document.querySelector("#passwordInput"),
  rememberMe: document.querySelector("#rememberMe"),
  loginMessage: document.querySelector("#loginMessage"),
  activeUserName: document.querySelector("#activeUserName"),
  logoutButton: document.querySelector("#logoutButton"),
  openChangePasswordButton: document.querySelector("#openChangePasswordButton"),
  changePasswordModal: document.querySelector("#changePasswordModal"),
  closeChangePasswordModalButton: document.querySelector("#closeChangePasswordModalButton"),
  changePasswordForm: document.querySelector("#changePasswordForm"),
  newPasswordInput: document.querySelector("#newPasswordInput"),
  confirmNewPasswordInput: document.querySelector("#confirmNewPasswordInput"),
  changePasswordMessage: document.querySelector("#changePasswordMessage"),
  openForgotPasswordButton: document.querySelector("#openForgotPasswordButton"),
  forgotPasswordModal: document.querySelector("#forgotPasswordModal"),
  closeForgotPasswordButton: document.querySelector("#closeForgotPasswordButton"),
  forgotPasswordForm: document.querySelector("#forgotPasswordForm"),
  forgotPasswordEmail: document.querySelector("#forgotPasswordEmail"),
  forgotPasswordMessage: document.querySelector("#forgotPasswordMessage"),
  passwordResetRequestsPanel: document.querySelector("#passwordResetRequestsPanel"),
  passwordResetRequestsMeta: document.querySelector("#passwordResetRequestsMeta"),
  passwordResetRequestsBoard: document.querySelector("#passwordResetRequestsBoard"),
  navLinks: document.querySelectorAll(".sidebar-link[data-view]"),
  homePage: document.querySelector("#homePage"),
  usersPage: document.querySelector("#usersPage"),
  approvalsPage: document.querySelector("#approvalsPage"),
  compliancePage: document.querySelector("#compliancePage"),
  complianceStartDate: document.querySelector("#complianceStartDate"),
  complianceEndDate: document.querySelector("#complianceEndDate"),
  complianceMeta: document.querySelector("#complianceMeta"),
  complianceBoard: document.querySelector("#complianceBoard"),
  complianceEmptyState: document.querySelector("#complianceEmptyState"),
  resyncSubmissionReportButton: document.querySelector("#resyncSubmissionReportButton"),
  resyncSubmissionReportMessage: document.querySelector("#resyncSubmissionReportMessage"),
  buddyPage: document.querySelector("#buddyPage"),
  contactsPage: document.querySelector("#contactsPage"),
  contactsCount: document.querySelector("#contactsCount"),
  contactsSearchInput: document.querySelector("#contactsSearchInput"),
  contactsTableBody: document.querySelector("#contactsTableBody"),
  contactsMobileCards: document.querySelector("#contactsMobileCards"),
  contactsEmptyState: document.querySelector("#contactsEmptyState"),
  contactsPagination: document.querySelector("#contactsPagination"),
  approvalsDateInput: document.querySelector("#approvalsDateInput"),
  approvalsTabNav: document.querySelector("#approvalsTabNav"),
  approvalsPendingTabCount: document.querySelector("#approvalsPendingTabCount"),
  approvalsCompletedTabCount: document.querySelector("#approvalsCompletedTabCount"),
  approvalsNotCompletedTabCount: document.querySelector("#approvalsNotCompletedTabCount"),
  approvalsApprovedTabCount: document.querySelector("#approvalsApprovedTabCount"),
  approvalsPendingSection: document.querySelector("#approvalsPendingSection"),
  approvalsCompletedSection: document.querySelector("#approvalsCompletedSection"),
  approvalsNotCompletedSection: document.querySelector("#approvalsNotCompletedSection"),
  approvalsApprovedSection: document.querySelector("#approvalsApprovedSection"),
  approvalsPendingMeta: document.querySelector("#approvalsPendingMeta"),
  approvalsPendingBoard: document.querySelector("#approvalsPendingBoard"),
  approvalsPendingEmpty: document.querySelector("#approvalsPendingEmpty"),
  approvalsPendingPagination: document.querySelector("#approvalsPendingPagination"),
  approvalsCompletedMeta: document.querySelector("#approvalsCompletedMeta"),
  approvalsCompletedBoard: document.querySelector("#approvalsCompletedBoard"),
  approvalsCompletedEmpty: document.querySelector("#approvalsCompletedEmpty"),
  approvalsCompletedPagination: document.querySelector("#approvalsCompletedPagination"),
  approvalsNotCompletedMeta: document.querySelector("#approvalsNotCompletedMeta"),
  approvalsNotCompletedBoard: document.querySelector("#approvalsNotCompletedBoard"),
  approvalsNotCompletedEmpty: document.querySelector("#approvalsNotCompletedEmpty"),
  approvalsNotCompletedPagination: document.querySelector("#approvalsNotCompletedPagination"),
  approvalsApprovedMeta: document.querySelector("#approvalsApprovedMeta"),
  approvalsApprovedBoard: document.querySelector("#approvalsApprovedBoard"),
  approvalsApprovedEmpty: document.querySelector("#approvalsApprovedEmpty"),
  approvalsApprovedPagination: document.querySelector("#approvalsApprovedPagination"),
  approvalsLiveTabCount: document.querySelector("#approvalsLiveTabCount"),
  approvalsLiveSection: document.querySelector("#approvalsLiveSection"),
  approvalsLiveMeta: document.querySelector("#approvalsLiveMeta"),
  liveLocationMap: document.querySelector("#liveLocationMap"),
  approvalsLiveEmpty: document.querySelector("#approvalsLiveEmpty"),
  approvalsLiveList: document.querySelector("#approvalsLiveList"),
  liveShareBanner: document.querySelector("#liveShareBanner"),
  sidebarToggle: document.querySelector("#sidebarToggle"),
  sidebarClose: document.querySelector("#sidebarClose"),
  totalUsers: document.querySelector("#totalUsers"),
  adminUsers: document.querySelector("#adminUsers"),
  salesUsers: document.querySelector("#salesUsers"),
  installerUsers: document.querySelector("#installerUsers"),
  buddyCount: document.querySelector("#buddyCount"),
  weekOffCount: document.querySelector("#weekOffCount"),
  absenceCount: document.querySelector("#absenceCount"),
  coverageTaskCount: document.querySelector("#coverageTaskCount"),
  addUserForm: document.querySelector("#addUserForm"),
  toggleAddUserForm: document.querySelector("#toggleAddUserForm"),
  userStatsStrip: document.querySelector("#userStatsStrip"),
  userDirectoryPanel: document.querySelector("#userDirectoryPanel"),
  newUserName: document.querySelector("#newUserName"),
  newUserEmail: document.querySelector("#newUserEmail"),
  newUserRole: document.querySelector("#newUserRole"),
  newUserDesignation: document.querySelector("#newUserDesignation"),
  newUserCode: document.querySelector("#newUserCode"),
  newUserDayOff: document.querySelector("#newUserDayOff"),
  newUserPassword: document.querySelector("#newUserPassword"),
  addUserMessage: document.querySelector("#addUserMessage"),
  searchInput: document.querySelector("#searchInput"),
  roleFilter: document.querySelector("#roleFilter"),
  dayOffFilter: document.querySelector("#dayOffFilter"),
  userTableBody: document.querySelector("#userTableBody"),
  mobileCards: document.querySelector("#mobileCards"),
  emptyState: document.querySelector("#emptyState"),
  userTablePagination: document.querySelector("#userTablePagination"),
  homeTitle: document.querySelector("#homeTitle"),
  homeSubtitle: document.querySelector("#homeSubtitle"),
  adminDashboardPanel: document.querySelector("#adminDashboardPanel"),
  pcDashboardPanel: document.querySelector("#pcDashboardPanel"),
  employeeDashboardPanel: document.querySelector("#employeeDashboardPanel"),
  buddyCoverageBanner: document.querySelector("#buddyCoverageBanner"),
  adminWelcome: document.querySelector("#adminWelcome"),
  pcDashboardWelcome: document.querySelector("#pcDashboardWelcome"),
  employeeWelcome: document.querySelector("#employeeWelcome"),
  homeSearchInput: document.querySelector("#homeSearchInput"),
  dashboardDateInput: document.querySelector("#dashboardDateInput"),
  openAssignTaskButton: document.querySelector("#openAssignTaskButton"),
  adminBoardMeta: document.querySelector("#adminBoardMeta"),
  employeeBoardMeta: document.querySelector("#employeeBoardMeta"),
  adminTaskBoard: document.querySelector("#adminTaskBoard"),
  walkinCustomerMeta: document.querySelector("#walkinCustomerMeta"),
  walkinCustomerBoard: document.querySelector("#walkinCustomerBoard"),
  pcMonitorDateInput: document.querySelector("#pcMonitorDateInput"),
  pcMonitorTabNav: document.querySelector("#pcMonitorTabNav"),
  pcPendingTabCount: document.querySelector("#pcPendingTabCount"),
  pcNotCompletedTabCount: document.querySelector("#pcNotCompletedTabCount"),
  pcCompletedTabCount: document.querySelector("#pcCompletedTabCount"),
  pcPendingSection: document.querySelector("#pcPendingSection"),
  pcPendingMeta: document.querySelector("#pcPendingMeta"),
  pcPendingBoard: document.querySelector("#pcPendingBoard"),
  pcPendingEmpty: document.querySelector("#pcPendingEmpty"),
  pcPendingPagination: document.querySelector("#pcPendingPagination"),
  pcNotCompletedSection: document.querySelector("#pcNotCompletedSection"),
  pcNotCompletedMeta: document.querySelector("#pcNotCompletedMeta"),
  pcNotCompletedBoard: document.querySelector("#pcNotCompletedBoard"),
  pcNotCompletedEmpty: document.querySelector("#pcNotCompletedEmpty"),
  pcNotCompletedPagination: document.querySelector("#pcNotCompletedPagination"),
  pcCompletedSection: document.querySelector("#pcCompletedSection"),
  pcCompletedMeta: document.querySelector("#pcCompletedMeta"),
  pcCompletedBoard: document.querySelector("#pcCompletedBoard"),
  pcCompletedEmpty: document.querySelector("#pcCompletedEmpty"),
  pcCompletedPagination: document.querySelector("#pcCompletedPagination"),
  pcTodaySummary: document.querySelector("#pcTodaySummary"),
  pcSubmittedMeta: document.querySelector("#pcSubmittedMeta"),
  pcSubmittedBoard: document.querySelector("#pcSubmittedBoard"),
  pcSubmittedEmpty: document.querySelector("#pcSubmittedEmpty"),
  pcSubmittedPagination: document.querySelector("#pcSubmittedPagination"),
  pantryAlertsSection: document.querySelector("#pantryAlertsSection"),
  pantryAlertsToggle: document.querySelector("#pantryAlertsToggle"),
  pantryAlertsMeta: document.querySelector("#pantryAlertsMeta"),
  pantryAlertsBoard: document.querySelector("#pantryAlertsBoard"),
  adminDashboardMain: document.querySelector("#adminDashboardMain"),
  kamalApprovalSection: document.querySelector("#kamalApprovalSection"),
  kamalApprovalMeta: document.querySelector("#kamalApprovalMeta"),
  kamalApprovalBoard: document.querySelector("#kamalApprovalBoard"),
  kamalFuelRequestsSection: document.querySelector("#kamalFuelRequestsSection"),
  kamalFuelRequestsMeta: document.querySelector("#kamalFuelRequestsMeta"),
  kamalFuelRequestsBoard: document.querySelector("#kamalFuelRequestsBoard"),
  fuelApprovalSection: document.querySelector("#fuelApprovalSection"),
  fuelApprovalMeta: document.querySelector("#fuelApprovalMeta"),
  fuelApprovalBoard: document.querySelector("#fuelApprovalBoard"),
  arunApprovalSection: document.querySelector("#arunApprovalSection"),
  arunApprovalMeta: document.querySelector("#arunApprovalMeta"),
  arunApprovalBoard: document.querySelector("#arunApprovalBoard"),
  employeeTaskTableBody: document.querySelector("#employeeTaskTableBody"),
  employeeTaskPagination: document.querySelector("#employeeTaskPagination"),
  vehicleChangeSection: document.querySelector("#vehicleChangeSection"),
  vehicleWorkflowTitle: document.querySelector("#vehicleWorkflowTitle"),
  vehicleWorkflowMeta: document.querySelector("#vehicleWorkflowMeta"),
  vehicleWorkflowBoard: document.querySelector("#vehicleWorkflowBoard"),
  dateRangeSelect: document.querySelector("#dateRangeSelect"),
  taskSelect: document.querySelector("#taskSelect"),
  departmentSelect: document.querySelector("#departmentSelect"),
  adminBoardPagination: document.querySelector("#adminBoardPagination"),
  assignTaskModal: document.querySelector("#assignTaskModal"),
  assignTaskModalTitle: document.querySelector("#assignTaskModalTitle"),
  closeAssignTaskButton: document.querySelector("#closeAssignTaskButton"),
  assignTaskForm: document.querySelector("#assignTaskForm"),
  assignTaskUser: document.querySelector("#assignTaskUser"),
  assignTaskUserList: document.querySelector("#assignTaskUserList"),
  assignTaskTitle: document.querySelector("#assignTaskTitle"),
  assignTaskFrequency: document.querySelector("#assignTaskFrequency"),
  assignTaskDepartment: document.querySelector("#assignTaskDepartment"),
  assignTaskPlanned: document.querySelector("#assignTaskPlanned"),
  assignTaskId: document.querySelector("#assignTaskId"),
  assignTaskSequence: document.querySelector("#assignTaskSequence"),
  assignTaskDetails: document.querySelector("#assignTaskDetails"),
  assignTaskSubmitButton: document.querySelector("#assignTaskSubmitButton"),
  assignTaskMessage: document.querySelector("#assignTaskMessage"),
  absenceForm: document.querySelector("#absenceForm"),
  absenceEmployeeInput: document.querySelector("#absenceEmployeeInput"),
  absenceEmployeeList: document.querySelector("#absenceEmployeeList"),
  absenceDateInput: document.querySelector("#absenceDateInput"),
  absenceReasonSelect: document.querySelector("#absenceReasonSelect"),
  absenceMessage: document.querySelector("#absenceMessage"),
  coverageList: document.querySelector("#coverageList"),
  checklistModal: document.querySelector("#checklistModal"),
  closeChecklistButton: document.querySelector("#closeChecklistButton"),
  checklistForm: document.querySelector("#checklistForm"),
  checklistTaskTitle: document.querySelector("#checklistTaskTitle"),
  checklistTaskMeta: document.querySelector("#checklistTaskMeta"),
  checklistFields: document.querySelector("#checklistFields"),
  checklistMessage: document.querySelector("#checklistMessage"),
  checklistSubmitRow: document.querySelector("#checklistSubmitRow"),
  notCompletedModal: document.querySelector("#notCompletedModal"),
  closeNotCompletedButton: document.querySelector("#closeNotCompletedButton"),
  notCompletedForm: document.querySelector("#notCompletedForm"),
  notCompletedTaskTitle: document.querySelector("#notCompletedTaskTitle"),
  notCompletedRemarks: document.querySelector("#notCompletedRemarks"),
  notCompletedMicButton: document.querySelector("#notCompletedMicButton"),
  notCompletedVoiceStatus: document.querySelector("#notCompletedVoiceStatus"),
  notCompletedMessage: document.querySelector("#notCompletedMessage"),
  submissionDetailsModal: document.querySelector("#submissionDetailsModal"),
  closeSubmissionDetailsButton: document.querySelector("#closeSubmissionDetailsButton"),
  submissionDetailsTitle: document.querySelector("#submissionDetailsTitle"),
  submissionDetailsMeta: document.querySelector("#submissionDetailsMeta"),
  submissionDetailsBody: document.querySelector("#submissionDetailsBody"),
};
